language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - "chmod +x ./gradlew"
  - "chmod +x gradle/wrapper/gradle-wrapper.jar"

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository/'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      - ksj3452@naver.com